apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deli-argentina
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/sela-tracks/1101/meital/final-project/application/application
    targetRevision: HEAD
    path: ./meitalchart
    helm:
      parameters:
        - name: image.repository
          value: meitalle/deli-argentina-img
        - name: image.tag
          value: latest
        - name: image.pullPolicy
          value: Always

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
