apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deli-argentina-release
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://gitlab.com/sela-tracks/1101/meital/final-project/application/application.git'
    path: ./meitalchart
    targetRevision: HEAD
    helm:
      parameters:
        - name: image.repository 
          value: meitalle/deli-argentina-img 
        - name: image.tag 
          value: latest
        - name: image.pullPolicy
          value: Always
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mongodb
    targetRevision: "14.12.3"
    helm:
      parameters:
        - name: auth.rootPassword
          value: ""  # Disable authentication
        - name: architecture
          value: "standalone"
        - name: persistence.enabled
          value: "true"
        - name: persistence.size
          value: 8Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

