version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/deli_argentina_db
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_URI=mongodb://mongodb:27017/test_deli_argentina_db
    depends_on:
      - mongodb

volumes:
  mongodb_data:
